# Polygon CDK Infrastructure Template
# This file is auto-generated by ChainiForge

provider "aws" {
  region = var.aws_region
}

resource "aws_instance" "sequencer" {
  ami           = "ami-0c55b159cbfafe1f0"
  instance_type = "t3.xlarge"

  tags = {
    Name = "Polygon-CDK-Sequencer"
    Network = var.network_name
  }
  
  # Configuration for CDK Sequencer binary
  user_data = <<-EOF
              #!/bin/bash
              curl -L https://github.com/0xPolygon/cdk-binaries/releases/latest/download/sequencer -o /usr/local/bin/sequencer
              chmod +x /usr/local/bin/sequencer
              sequencer run --config /etc/cdk/sequencer.json
              EOF
}

resource "aws_db_instance" "state_db" {
  allocated_storage    = 100
  engine               = "postgres"
  engine_version       = "13.7"
  instance_class       = "db.t3.large"
  name                 = "cdk_state"
  username             = "admin"
  password             = var.db_password
}

# Add more resources for Aggregator, Prover, etc.
